package cn.dlpu.oa.domain;

// Generated 2016-9-22 21:15:50 by Hibernate Tools 3.4.0.CR1

import lombok.*;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Medicine generated by hbm2java
 */
@Setter
@Getter
@AllArgsConstructor
@NoArgsConstructor
public class Medicine implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private String name;
	private String chemFormula;
	private String manufacturer;
	private Date manuDate;
	private Date expireDate;
	private String position;
	private String concentration;
	private String reverse;
	private User owner;
	private Set<Record> records = new HashSet<Record>();
	private Set<Solution> solutions = new HashSet<Solution>();

	public Set<Solution> getSolutions() {
		return solutions;
	}

	public void setSolutions(Set<Solution> solutions) {
		this.solutions = solutions;
	}

//	public Medicine() {}

	public Medicine(String name, Date manuDate, Date expireDate) {
		this.name = name;
		this.manuDate = manuDate;
		this.expireDate = expireDate;
	}

	public Medicine(String name, String chemFormula, String manufacturer,
			Date manuDate, Date expireDate, String position,
			String concentration, String reverse, User owner, Set<Record> records, Set<Solution> solutions) {
		this.name = name;
		this.chemFormula = chemFormula;
		this.manufacturer = manufacturer;
		this.manuDate = manuDate;
		this.expireDate = expireDate;
		this.position = position;
		this.concentration = concentration;
		this.reverse = reverse;
		this.owner = owner;
		this.records = records;
		this.solutions = solutions;
	}
//
//	public Integer getId() {
//		return this.id;
//	}
//
//	public void setId(Integer id) {
//		this.id = id;
//	}
//
//	public String getName() {
//		return this.name;
//	}
//
//	public void setName(String name) {
//		this.name = name;
//	}
//
//	public String getChemFormula() {
//		return this.chemFormula;
//	}
//
//	public void setChemFormula(String chemFormula) {
//		this.chemFormula = chemFormula;
//	}
//
//	public String getManufacturer() {
//		return this.manufacturer;
//	}
//
//	public void setManufacturer(String manufacturer) {
//		this.manufacturer = manufacturer;
//	}
//
//	public Date getManuDate() {
//		return this.manuDate;
//	}
//
//	public void setManuDate(Date manuDate) {
//		this.manuDate = manuDate;
//	}
//
//	public Date getExpireDate() {
//		return this.expireDate;
//	}
//
//	public void setExpireDate(Date expireDate) {
//		this.expireDate = expireDate;
//	}
//
//	public String getPosition() {
//		return this.position;
//	}
//
//	public void setPosition(String position) {
//		this.position = position;
//	}
//
//	public String getConcentration() {
//		return this.concentration;
//	}
//
//	public void setConcentration(String concentration) {
//		this.concentration = concentration;
//	}
//
//	public String getReverse() {
//		return this.reverse;
//	}
//
//	public void setReverse(String reverse) {
//		this.reverse = reverse;
//	}
//
//	public Set<Record> getRecords() {
//		return records;
//	}
//
//	public void setRecords(Set<Record> records) {
//		this.records = records;
//	}
//
//	public User getOwner() {
//		return owner;
//	}
//
//	public void setOwner(User owner) {
//		this.owner = owner;
//	}

}
