package cn.dlpu.oa.domain;

// Generated 2016-9-22 21:15:50 by Hibernate Tools 3.4.0.CR1

import lombok.*;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Project generated by hbm2java
 */
@AllArgsConstructor
@Getter
@Setter
@NoArgsConstructor
public class Project implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private String projNo;
	private String name;
	private Date startDate;
	private Date endDate;
	private String reverse;
	private User claimer;
	private Set<Experiment> experiments = new HashSet<Experiment>();

//	public Project() {}

	public Project(String projNo, Date startDate, Date endDate) {
		this.projNo = projNo;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	public Project(String projNo, String name, Date startDate, Date endDate,
			String reverse, User claimer, Set<Experiment> experiments) {
		this.projNo = projNo;
		this.name = name;
		this.startDate = startDate;
		this.endDate = endDate;
		this.reverse = reverse;
		this.claimer = claimer;
		this.experiments = experiments;
	}
//
//	public Integer getId() {
//		return this.id;
//	}
//
//	public void setId(Integer id) {
//		this.id = id;
//	}
//
//	public String getProjNo() {
//		return this.projNo;
//	}
//
//	public void setProjNo(String projNo) {
//		this.projNo = projNo;
//	}
//
//	public String getName() {
//		return this.name;
//	}
//
//	public void setName(String name) {
//		this.name = name;
//	}
//
//	public Date getStartDate() {
//		return this.startDate;
//	}
//
//	public void setStartDate(Date startDate) {
//		this.startDate = startDate;
//	}
//
//	public Date getEndDate() {
//		return this.endDate;
//	}
//
//	public void setEndDate(Date endDate) {
//		this.endDate = endDate;
//	}
//
//	public String getReverse() {
//		return this.reverse;
//	}
//
//	public void setReverse(String reverse) {
//		this.reverse = reverse;
//	}
//
//	public User getClaimer() {
//		return claimer;
//	}
//
//	public void setClaimer(User claimer) {
//		this.claimer = claimer;
//	}
//
//	public Set<Experiment> getExperiments() {
//		return experiments;
//	}
//
//	public void setExperiments(Set<Experiment> experiments) {
//		this.experiments = experiments;
//	}

}
