package cn.dlpu.oa.domain;

// Generated 2016-9-22 21:15:50 by Hibernate Tools 3.4.0.CR1

import lombok.*;

/**
 * ExperimentSolution generated by hbm2java
 */
@AllArgsConstructor
@Getter
@Setter
@NoArgsConstructor
public class RecordSolution implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private int recordId;
	private int solutionId;

//	public RecordSolution() {}

	public RecordSolution(int recordId, int solutionId) {
		this.recordId = recordId;
		this.solutionId = solutionId;
	}
//
//	public Integer getId() {
//		return this.id;
//	}
//
//	public void setId(Integer id) {
//		this.id = id;
//	}
//
//	public int getRecordId() {
//		return this.recordId;
//	}
//
//	public void setRecordId(int recordId) {
//		this.recordId = recordId;
//	}
//
//	public int getSolutionId() {
//		return this.solutionId;
//	}
//
//	public void setSolutionId(int solutionId) {
//		this.solutionId = solutionId;
//	}

}
