package cn.dlpu.oa.domain;

// Generated 2016-9-22 21:15:50 by Hibernate Tools 3.4.0.CR1

import lombok.*;

/**
 * RecordUser generated by hbm2java
 */
@AllArgsConstructor
@Getter
@Setter
@NoArgsConstructor
public class RecordUser implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private int recordId;
	private int userId;

//	public RecordUser() {}

	public RecordUser(int recordId, int userId) {
		this.recordId = recordId;
		this.userId = userId;
	}
//
//	public Integer getId() {
//		return this.id;
//	}
//
//	public void setId(Integer id) {
//		this.id = id;
//	}
//
//	public int getRecordId() {
//		return this.recordId;
//	}
//
//	public void setRecordId(int recordId) {
//		this.recordId = recordId;
//	}
//
//	public int getUserId() {
//		return this.userId;
//	}
//
//	public void setUserId(int userId) {
//		this.userId = userId;
//	}

}
