package cn.dlpu.oa.domain;

// Generated 2016-9-22 21:15:50 by Hibernate Tools 3.4.0.CR1

import lombok.*;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Record generated by hbm2java
 */
@AllArgsConstructor
@Getter
@Setter
@NoArgsConstructor
public class Record implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private String recordNo;
	private String name;
	private Experiment experiment;
	private Medicine substrate;
	private String substrateMass;
	private String cladLayer;
	private String ph;
	private String temperature;
	private String reaTime;
	private String process;
	private Date startDate;
	private Date endDate;
	private String reverse;
	private Set<Specimen> specimens = new HashSet<Specimen>();
	private Set<Solution> solutions = new HashSet<Solution>();
	private Set<User> operaters = new HashSet<User>();

//	public Record() {}

	public Record(String recordNo, Experiment experiment, Medicine substrate,
			String substrateMass, String cladLayer, String ph,
			String temperature, String reaTime, Date startDate, Date endDate) {
		this.recordNo = recordNo;
		this.experiment = experiment;
		this.substrate = substrate;
		this.substrateMass = substrateMass;
		this.cladLayer = cladLayer;
		this.ph = ph;
		this.temperature = temperature;
		this.reaTime = reaTime;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	public Record(String recordNo, String name, Experiment experiment, Medicine substrate,
			String substrateMass, String cladLayer, String ph,
			String temperature, String reaTime, String process, Date startDate,
			Date endDate, String reverse, Set<Solution> solutions, Set<User> operaters, Set<Specimen> specimens) {
		this.recordNo = recordNo;
		this.name = name;
		this.experiment = experiment;
		this.substrate = substrate;
		this.substrateMass = substrateMass;
		this.cladLayer = cladLayer;
		this.ph = ph;
		this.temperature = temperature;
		this.reaTime = reaTime;
		this.process = process;
		this.startDate = startDate;
		this.endDate = endDate;
		this.reverse = reverse;
		this.solutions = solutions;
		this.operaters = operaters;
		this.specimens = specimens;
	}
//
//	public Integer getId() {
//		return this.id;
//	}
//
//	public void setId(Integer id) {
//		this.id = id;
//	}
//
//	public String getRecordNo() {
//		return this.recordNo;
//	}
//
//	public void setRecordNo(String recordNo) {
//		this.recordNo = recordNo;
//	}
//
//	public String getName() {
//		return this.name;
//	}
//
//	public void setName(String name) {
//		this.name = name;
//	}
//
//	public Experiment getExperiment() {
//		return experiment;
//	}
//
//	public void setExperiment(Experiment experiment) {
//		this.experiment = experiment;
//	}
//
//	public Medicine getSubstrate() {
//		return substrate;
//	}
//
//	public void setSubstrate(Medicine substrate) {
//		this.substrate = substrate;
//	}
//
//	public String getSubstrateMass() {
//		return this.substrateMass;
//	}
//
//	public void setSubstrateMass(String substrateMass) {
//		this.substrateMass = substrateMass;
//	}
//
//	public String getCladLayer() {
//		return this.cladLayer;
//	}
//
//	public void setCladLayer(String cladLayer) {
//		this.cladLayer = cladLayer;
//	}
//
//	public String getTemperature() {
//		return this.temperature;
//	}
//
//	public void setTemperature(String temperature) {
//		this.temperature = temperature;
//	}
//
//	public String getReaTime() {
//		return this.reaTime;
//	}
//
//	public void setReaTime(String reaTime) {
//		this.reaTime = reaTime;
//	}
//
//	public String getProcess() {
//		return this.process;
//	}
//
//	public void setProcess(String process) {
//		this.process = process;
//	}
//
//	public Date getStartDate() {
//		return this.startDate;
//	}
//
//	public void setStartDate(Date startDate) {
//		this.startDate = startDate;
//	}
//
//	public Date getEndDate() {
//		return this.endDate;
//	}
//
//	public void setEndDate(Date endDate) {
//		this.endDate = endDate;
//	}
//
//	public String getReverse() {
//		return this.reverse;
//	}
//
//	public void setReverse(String reverse) {
//		this.reverse = reverse;
//	}
//
//	public Set<Solution> getSolutions() {
//		return solutions;
//	}
//
//	public void setSolutions(Set<Solution> solutions) {
//		this.solutions = solutions;
//	}
//
//	public Set<User> getOperaters() {
//		return operaters;
//	}
//
//	public void setOperaters(Set<User> operaters) {
//		this.operaters = operaters;
//	}
//
//	public Set<Specimen> getSpecimens() {
//		return specimens;
//	}
//
//	public void setSpecimens(Set<Specimen> specimens) {
//		this.specimens = specimens;
//	}
//
//	public String getPh() {
//		return ph;
//	}
//
//	public void setPh(String ph) {
//		this.ph = ph;
//	}

}
