package cn.dlpu.oa.domain;

// Generated 2016-9-22 21:15:50 by Hibernate Tools 3.4.0.CR1

import lombok.*;

/**
 * SoluMedi generated by hbm2java
 */
@AllArgsConstructor
@Getter
@Setter
@NoArgsConstructor
public class SoluMedi implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private int solutionId;
	private int medicineId;

//	public SoluMedi() {
//	}

	public SoluMedi(int solutionId, int medicineId) {
		this.solutionId = solutionId;
		this.medicineId = medicineId;
	}
//
//	public Integer getId() {
//		return this.id;
//	}
//
//	public void setId(Integer id) {
//		this.id = id;
//	}
//
//	public int getSolutionId() {
//		return this.solutionId;
//	}
//
//	public void setSolutionId(int solutionId) {
//		this.solutionId = solutionId;
//	}
//
//	public int getMedicineId() {
//		return this.medicineId;
//	}
//
//	public void setMedicineId(int medicineId) {
//		this.medicineId = medicineId;
//	}

}
