package cn.dlpu.oa.domain;

import lombok.*;

import java.util.HashSet;
import java.util.Set;

// Generated 2016-9-22 21:15:50 by Hibernate Tools 3.4.0.CR1

/**
 * Specimen generated by hbm2java
 */
@AllArgsConstructor
@Getter
@Setter
@NoArgsConstructor
public class Specimen implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private String label;
//	private String detectResult;
	private Record record;
	private String reverse;
	private String reverse1;
	private User owner;
//	private String detectLabel;
//	private Date submitDate;
//	private Date detectDate;
//	private String detectMean;
	private Set<Test> tests = new HashSet<Test>();

//	public Specimen() {
//	}

	public Specimen(String label, Record record,
			String reverse, String reverse1, User owner, Set<Test> tests) {
		this.label = label;
		this.record = record;
		this.reverse = reverse;
		this.reverse1 = reverse1;
		this.owner = owner;
		this.tests = tests;
	}
//
//	public Integer getId() {
//		return this.id;
//	}
//
//	public void setId(Integer id) {
//		this.id = id;
//	}
//
//	public String getLabel() {
//		return this.label;
//	}
//
//	public void setLabel(String label) {
//		this.label = label;
//	}
//
//	public Record getRecord() {
//		return record;
//	}
//
//	public void setRecord(Record record) {
//		this.record = record;
//	}
//
//	public String getReverse() {
//		return this.reverse;
//	}
//
//	public void setReverse(String reverse) {
//		this.reverse = reverse;
//	}
//
//	public String getReverse1() {
//		return reverse1;
//	}
//
//	public void setReverse1(String reverse1) {
//		this.reverse1 = reverse1;
//	}
//
//	public User getOwner() {
//		return owner;
//	}
//
//	public void setOwner(User owner) {
//		this.owner = owner;
//	}
//
//	public static long getSerialversionuid() {
//		return serialVersionUID;
//	}
//
//	public Set<Test> getTests() {
//		return tests;
//	}
//
//	public void setTests(Set<Test> tests) {
//		this.tests = tests;
//	}

}
