package cn.dlpu.oa.domain;

// Generated 2016-9-22 21:15:50 by Hibernate Tools 3.4.0.CR1

import lombok.*;

import java.util.Date;

/**
 * StageSummary generated by hbm2java
 */
@AllArgsConstructor
@Getter
@Setter
@NoArgsConstructor
public class StageSummary implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private String title;
	private User author;
	private String summary1;
	private String summary2;
	private String summary3;
	private Date summaryDate;
	private Date lastUpdateDate;
	private String reverse;

//	public StageSummary() {
//	}

	public StageSummary(String summary1, Date summaryDate, Date lastUpdateDate) {
		this.summary1 = summary1;
		this.summaryDate = summaryDate;
		this.lastUpdateDate = lastUpdateDate;
	}

	public StageSummary(String title, User author, String summary1, String summary2,
			String summary3, Date summaryDate, Date lastUpdateDate, String reverse) {
		this.title = title;
		this.author = author;
		this.summary1 = summary1;
		this.summary2 = summary2;
		this.summary3 = summary3;
		this.summaryDate = summaryDate;
		this.lastUpdateDate = lastUpdateDate;
		this.reverse = reverse;
	}
//
//	public Integer getId() {
//		return this.id;
//	}
//
//	public void setId(Integer id) {
//		this.id = id;
//	}
//
//	public User getAuthor() {
//		return author;
//	}
//
//	public void setAuthor(User author) {
//		this.author = author;
//	}
//
//	public String getSummary1() {
//		return this.summary1;
//	}
//
//	public void setSummary1(String summary1) {
//		this.summary1 = summary1;
//	}
//
//	public String getSummary2() {
//		return this.summary2;
//	}
//
//	public void setSummary2(String summary2) {
//		this.summary2 = summary2;
//	}
//
//	public String getSummary3() {
//		return this.summary3;
//	}
//
//	public void setSummary3(String summary3) {
//		this.summary3 = summary3;
//	}
//
//	public String getReverse() {
//		return this.reverse;
//	}
//
//	public void setReverse(String reverse) {
//		this.reverse = reverse;
//	}
//
//	public Date getSummaryDate() {
//		return summaryDate;
//	}
//
//	public void setSummaryDate(Date summaryDate) {
//		this.summaryDate = summaryDate;
//	}
//
//	public Date getLastUpdateDate() {
//		return lastUpdateDate;
//	}
//
//	public void setLastUpdateDate(Date lastUpdateDate) {
//		this.lastUpdateDate = lastUpdateDate;
//	}
//
//	public static long getSerialversionuid() {
//		return serialVersionUID;
//	}
//
//	public String getTitle() {
//		return title;
//	}
//
//	public void setTitle(String title) {
//		this.title = title;
//	}

}
