package cn.dlpu.oa.domain;

// Generated 2016-12-5 13:06:18 by Hibernate Tools 3.4.0.CR1

import lombok.*;

import java.util.Date;

/**
 * Test generated by hbm2java
 */
@AllArgsConstructor
@Getter
@Setter
@NoArgsConstructor
public class Test implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private String label;
	private Specimen specimen;
	private Date submitDate;
	private Date testDate;
	private String testMethod;
	private String testResult;
	private String reverse;
	private User owner;

//	public Test() {
//	}

	public Test(String label, Specimen specimen, Date submitDate,
			Date testDate, String testMethod, String testResult, String reverse, User owner) {
		this.label = label;
		this.specimen = specimen;
		this.submitDate = submitDate;
		this.testDate = testDate;
		this.testMethod = testMethod;
		this.testResult = testResult;
		this.reverse = reverse;
		this.owner = owner;
	}
//
//	public Integer getId() {
//		return this.id;
//	}
//
//	public void setId(Integer id) {
//		this.id = id;
//	}
//
//	public String getLabel() {
//		return this.label;
//	}
//
//	public void setLabel(String label) {
//		this.label = label;
//	}
//
//	public Specimen getSpecimen() {
//		return specimen;
//	}
//
//	public void setSpecimen(Specimen specimen) {
//		this.specimen = specimen;
//	}
//
//	public static long getSerialversionuid() {
//		return serialVersionUID;
//	}
//
//	public Date getSubmitDate() {
//		return this.submitDate;
//	}
//
//	public void setSubmitDate(Date submitDate) {
//		this.submitDate = submitDate;
//	}
//
//	public Date getTestDate() {
//		return this.testDate;
//	}
//
//	public void setTestDate(Date testDate) {
//		this.testDate = testDate;
//	}
//
//	public String getTestMethod() {
//		return this.testMethod;
//	}
//
//	public void setTestMethod(String testMethod) {
//		this.testMethod = testMethod;
//	}
//
//	public String getTestResult() {
//		return this.testResult;
//	}
//
//	public void setTestResult(String testResult) {
//		this.testResult = testResult;
//	}
//
//	public String getReverse() {
//		return this.reverse;
//	}
//
//	public void setReverse(String reverse) {
//		this.reverse = reverse;
//	}
//
//	public User getOwner() {
//		return owner;
//	}
//
//	public void setOwner(User owner) {
//		this.owner = owner;
//	}

}
